### ISSUE TITLE
Add libfmt to C++ Dependencies

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/simulator#15]
We want to use [libfmt](https://github.com/fmtlib/fmt) for formatting strings. 

- [x] Add libfmt installation to `cpp/scripts/setup-dependencies.sh`
- [x] Update `cpp/scripts/README.md`
- [x] Link libfmt in cmake
- [ ] Check and implement required libfmt configuration
- [x] Write test to check linking and existence of libfmt

**Comment by Ozaq** [comment]
@zeroset I don't get this:
> Check and implement required libfmt configuration

What is the task here?

**Comment by zeroset** [comment]
Ok actually there is no real configuration. Then i mean write a macro for `FMT_STRING` compile time format checking. Not that obvious  :D

**Comment by Ozaq** [comment]
I see, ill add this to the PR then :)
