### ISSUE TITLE
C++ Library Logging 

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/simulator#19]
Since the core C++ library should not write log files directly we want to register callbacks to call with the log messages.
The available Logging Levels should be: Debug, Info, Warning, Error 

- [x] Define Callback signature (`callback(string or string_view or const char*)` ?)
- [x] Implement API Functions for registering Logging Callbacks
- [x] Without callback set it should be a nullop

**Comment by Ozaq** [comment]
Does anyone mind If I grab this one?

**Comment by Ozaq** [comment]
Last amendment should fix mscv/apple clang build failures
